name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - name: Build
        run: yarn build
        env:
          API_URL: 'https://api.edgeserver.io'
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.0.34
        with:
          app_id: '987654338'
          server: https://api.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: dist
